/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FenetreQuiz;

/**
 *
 * @author iyanarekiki
 */
import java.util.ArrayList;  

public class FenetreQuiz extends javax.swing.JFrame {
    private ArrayList<Question> questions;
    private int indexQuestionCourante = 0;
    private int score = 0;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
    
  
    /**
     * Creates new form FenetreQuiz
     */
  

    public FenetreQuiz() {
        initComponents();
        
         initialiserQuestions();
        afficherQuestionCourante();
    }    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        btnSuivante = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setText("jLabel1");

        btnRep1.setText("Question1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("Question2");

        btnRep3.setText("Question3");

        btnRep4.setText("Question4");

        lblFeedback.setText("Bonne réponse");

        btnSuivante.setText("Question suivante");

        lblScore.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnRep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRep4)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRep2)
                        .addGap(66, 66, 66)
                        .addComponent(btnRep3)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFeedback)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSuivante)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblQuestion)
                        .addGap(169, 169, 169))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblScore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblQuestion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep1)
                    .addComponent(btnRep4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep3)
                    .addComponent(btnRep2))
                .addGap(18, 18, 18)
                .addComponent(lblFeedback)
                .addGap(18, 18, 18)
                .addComponent(btnSuivante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblScore)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRep1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivante;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables


 private void initialiserQuestions() {
        ArrayList<Object> listeQuestions = new ArrayList<>();
       
        listeQuestions.add(new Question(
            "Quel mot-clé Java est utilisé pour garantir qu'une variable ne peut être modifiée après son initialisation ?",
            "static", "volatile", "final", "transient", 3));
        listeQuestions.add(new Question(
            "Que signifie l'acronyme 'CPU' ?",
            "Central Power Unit", "Computer Processing Utility", "Central Processing Unit", "Control Program Unit", 3));
        listeQuestions.add(new Question(
            "Quel langage est principalement utilisé pour définir le style d'une page web ?",
            "JavaScript", "HTML", "Python", "CSS", 4));
        listeQuestions.add(new Question(
            "Quelle clause SQL est utilisée pour filtrer les enregistrements d'un résultat de requête ?",
            "SELECT", "FROM", "WHERE", "ORDER BY", 3));
        listeQuestions.add(new Question(
            "Quel type de mémoire est volatile (perd ses données quand le courant est coupé) ?",
            "Disque Dur (HDD)", "SSD (Solid State Drive)", "RAM (Random Access Memory)", "ROM (Read-Only Memory)", 3));
    }
 private void afficherQuestionCourante() {
        if (indexQuestionCourante >= listeQuestions.size()) {
            return;
        }
       
        Question question = listeQuestions.get(indexQuestionCourante);
       
        lblQuestion.setText(question.getIntitule());
       
        btnRep1.setText(question.getProposition1());
        btnRep2.setText(question.getProposition2());
        btnRep3.setText(question.getProposition3());
        btnRep4.setText(question.getProposition4());
       
        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);
       
        QuestionSuivante.setEnabled(false);
       
        lblFeedback.setText("Choisissez une réponse...");
        lblScore.setText("Score : " + score + " / " + listeQuestions.size());
    }
   
    private void verifierReponse(int reponseChoisie) {
        Question questionCourante = listeQuestions.get(indexQuestionCourante);

        if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !!!");
            score++;
        } else {
            lblFeedback.setText("Mauvaise réponse. La bonne réponse était la proposition " + questionCourante.getIndexBonneReponse() + ".");
        }
       
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
       
        QuestionSuivante.setEnabled(true);
       
        lblScore.setText("Score : " + score + " / " + (indexQuestionCourante + 1));
    }
   
}
