/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author iyanarekiki
 */
import javax.swing.*;
import java.awt.*;

public class InterfaceCadenas extends javax.swing.JFrame {

    private final Cadenas jeu;

    // Tableau avec les 4 chiffres proposés par le joueur
    private int[] chiffresEssai = {0, 0, 0, 0};

    public InterfaceCadenas() {
        this.jeu = new Cadenas();     // création de la logique de jeu

        
        initComponents();             // construit l’interface générée par NetBeans
        miseAJourAffichage();         // met tout à zéro au démarrage

        // options de base de la fenêtre
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null); // centre la fenêtre
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouvez le bon code en moins de 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 8, -1, -1));

        texte_chiffre_0.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        texte_chiffre_0.setText("0");
        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        texte_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        texte_chiffre_1.setText("0");
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        texte_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        texte_chiffre_2.setText(" 0");
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 26, 38));

        texte_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        texte_chiffre_3.setText("0");
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        up_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        up_chiffre_1.setText("^");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        up_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        up_chiffre_2.setText("^");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        down_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        down_chiffre_1.setText("v");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        down_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        down_chiffre_2.setText("v");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        down_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        down_chiffre_3.setText("v");
        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        down_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        down_chiffre_4.setText("v");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        up_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        up_chiffre_4.setText("^");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        bouton_tester.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bouton_tester.setText("TESTER");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts:");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 252, -1, -1));

        texte_nb_chiffres_haut.setText("Nombre de chiffres trop hauts :");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, -1, -1));

        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 298, -1, -1));

        texte_tentatives.setText("Tentatives");
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 210, -1, -1));

        texte_score.setText("jLabel1");
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 239, -1, -1));

        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 268, -1, -1));

        up_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        up_chiffre_3.setText("^");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_1ActionPerformed
{
    chiffresEssai[0] = (chiffresEssai[0] + 1) % 10; // passe de 9 à 0
    miseAJourAffichage();
}

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        {
    chiffresEssai[1] = (chiffresEssai[1] + 1) % 10;
    miseAJourAffichage();
}
// TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        {
    chiffresEssai[1] = (chiffresEssai[1] + 9) % 10;
    miseAJourAffichage();
}
// TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
       {
    chiffresEssai[3] = (chiffresEssai[3] + 9) % 10;
    miseAJourAffichage();
} // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
      {
    chiffresEssai[3] = (chiffresEssai[3] + 1) % 10;
    miseAJourAffichage();
}
  // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
      // Si la partie est déjà finie, on bloque l'action
    if (jeu.estFini()) {
        JOptionPane.showMessageDialog(this, "La partie est terminée ! Cliquez sur Recommencer.");
        return;
    }
    
    // 1. Appel de la logique métier (met à jour les scores)
    jeu.verifierEssai(chiffresEssai);

    // 2. Mettre à jour l'interface avec les nouveaux résultats
    miseAJourAffichage();

    // 3. Vérifier les conditions de fin de partie
    if (jeu.estGagne()) {
        JOptionPane.showMessageDialog(this, "FÉLICITATIONS ! Vous avez trouvé le code !");
        bouton_tester.setEnabled(false); // Désactive le bouton Tester
    } else if (jeu.estPerdu()) {
        // Optionnel: Afficher le code secret (nécessite getCodeSecret dans Cadenas)
        // String code = Arrays.toString(jeu.getCodeSecret()).replaceAll("[\\[\\], ]", "");
        JOptionPane.showMessageDialog(this, "PERDU ! La partie est terminée.");
        bouton_tester.setEnabled(false); // Désactive le bouton Tester
    }  // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
     // 1. Réinitialiser la logique métier
    jeu.recommencer();
    
    // 2. Réinitialiser l'essai affiché à 0000
    chiffresEssai = new int[]{0, 0, 0, 0};
    
    // 3. Réactiver le bouton Tester
    bouton_tester.setEnabled(true);
    
    // 4. Mettre à jour l'affichage
    miseAJourAffichage();
    texte_chiffre_0.setText(String.valueOf(chiffresEssai[0]));
        texte_chiffre_1.setText(String.valueOf(chiffresEssai[1]));
        texte_chiffre_2.setText(String.valueOf(chiffresEssai[2]));
        texte_chiffre_3.setText(String.valueOf(chiffresEssai[3]));

        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts: " + jeu.getNombreChiffresExacts());
        texte_nb_chiffres_haut.setText("Nombre de chiffres trop hauts : " + jeu.getNombreChiffresTropHauts());
        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas : " + jeu.getNombreChiffresTropBas());

        texte_score.setText(jeu.getTentativesUtilisees() + " sur " + jeu.getMAX_TENTATIVES());
      // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
       {
    chiffresEssai[2] = (chiffresEssai[2] + 9) % 10;
    miseAJourAffichage();
}
 // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
      {
    chiffresEssai[0] = (chiffresEssai[0] + 9) % 10;
    miseAJourAffichage();
}  // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
       {
    chiffresEssai[2] = (chiffresEssai[2] + 1) % 10;
    miseAJourAffichage();
}
 // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            // plus simple que logger.log(...)
            
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new InterfaceCadenas().setVisible(true));
    }

    private void construireComposants() {
        for (int i = 0; i < 4; i++) {
            JLabel[] chiffreLabels = null;
            chiffreLabels[i] = new JLabel(String.valueOf(chiffresEssai[i]));
            chiffreLabels[i].setFont(new Font("Arial", Font.BOLD, 48));
            chiffreLabels[i].setBounds(50 + i * 120, 100, 100, 60); // Positionnement absolu
            this.add(chiffreLabels[i]);
        }
        
              
        // ... Répétez pour tous les autres boutons et labels (flèches, score, etc.) ...
        
        // Initialiser l'affichage des scores à 0
        miseAJourAffichage();
        
        
    }

    private void miseAJourAffichage() { 
//  Mettre à jour l'affichage des 4 chiffres choisis par l'utilisateur
    texte_chiffre_0.setText(String.valueOf(chiffresEssai[0]));
    texte_chiffre_1.setText(String.valueOf(chiffresEssai[1]));
    texte_chiffre_2.setText(String.valueOf(chiffresEssai[2]));
    texte_chiffre_3.setText(String.valueOf(chiffresEssai[3]));

    // 2. Mettre à jour les résultats (Scores)
    // Nous mettons la valeur à côté du libellé descriptif.
    texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts: " + jeu.getNombreChiffresExacts());
    texte_nb_chiffres_haut.setText("Nombre de chiffres trop hauts : " + jeu.getNombreChiffresTropHauts());
    texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas : " + jeu.getNombreChiffresTropBas());

    // 3. Mettre à jour le score global (Tentatives)
    texte_score.setText(jeu.getTentativesUtilisees() + " sur " + jeu.getMAX_TENTATIVES());
        

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
